[build]
beforeDevCommand = "pnpm run --silent dev"
devPath = "http://127.0.0.1:3000"
beforeBuildCommand = "pnpm run --silent build"
distDir = "./ui/build"

[package]
productName = "Password Manager"
version = "0.2.0"

[tauri.allowlist.window]
startDragging = true

[[tauri.windows]]
title = "tauri pw manager"
width = 800
height = 600
decorations = false
transparent = true

[tauri.bundle]
identifier = "com.tauri.pw-manager"
active = true
targets = "all"
icon = [
  "assets/32x32.png",
  "assets/128x128.png",
  "assets/128x128@2x.png",
  "assets/icon.icns",
  "assets/icon.ico"
]
resources = []
copyright = ""
category = "Utility"
shortDescription = "Secure password manager"
longDescription = "A secure desktop password manager with strong encryption"

[tauri.bundle.macOS]
frameworks = []
minimumSystemVersion = "10.13"

[tauri.bundle.windows]
certificateThumbprint = ""
digestAlgorithm = "sha256"
timestampUrl = ""

[tauri.bundle.deb]
depends = []
